token: "__LICHESS_BOT_TOKEN__"
url: "https://lichess.org/"

engine:
  dir: "./engines"
  name: "xewali_engine"
  protocol: "uci"

challenge:
  concurrency: 1
  accept_bot: false
  only_bot: false
  max_base: 10800
  min_base: 30
  max_increment: 180
  min_increment: 0
  variants:
    - standard
    - chess960
  time_controls:
    - bullet
    - blitz
    - rapid
    - classical
  modes:
    - casual
    - rated
