token: "__LICHESS_BOT_TOKEN__"
url: "https://lichess.org/"

engine:
  dir: "./engines"
  name: "xewali_engine"
  protocol: "uci"

challenge:
  concurrency: 1
  accept_bot: false
  only_bot: false
  max_base: 900
  min_base: 600
  max_increment: 30
  min_increment: 10
  variants:
    - standard
  time_controls:
    - rapid
  modes:
    - casual
    - rated
